# Generated by Django 5.2 on 2025-06-08 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_dashboard_reloads_customuser_login_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='validated',
            field=models.BooleanField(default=False),
        ),
    ]
